Fix SonarCloud code coverage reporting
We have started seeing an error from SonarCloud when it tries to read our SimpleCov output file.

```bash
INFO: Sensor SimpleCov Sensor for Ruby coverage [ruby]
ERROR: Cannot read coverage report file, expecting standard SimpleCov resultset JSON format: 'coverage/.resultset.json'
java.lang.ClassCastException: org.sonarsource.analyzer.commons.internal.json.simple.JSONObject cannot be cast to org.sonarsource.analyzer.commons.internal.json.simple.JSONArray
	at org.sonarsource.ruby.plugin.SimpleCovSensor.mergeFrameworkCoverages(SimpleCovSensor.java:121)
	at org.sonarsource.ruby.plugin.SimpleCovSensor.mergeFileCoverages(SimpleCovSensor.java:114)
...
```

We know this to be because of the recent change to use the latest version of SimpleCov to resolve a security issue with the version of JSON it was using (see PR https://github.com/DEFRA/waste-carriers-front-office/pull/484). Since that was merged SonarCloud has been reporting 0% test coverage for the project.

This change ensures SonarCloud can read our code coverage again by reverting back to the previous version of [Simplecov](https://rubygems.org/gems/simplecov).

Note. This brings the [JSON](https://rubygems.org/gems/json/) dependency back in again which we were able to drop with our changes in #484. However, with the refresh, it's bringing in the latest version (2.3.0) which includes a fix for the issue Hakiri was previously flagging. So on a security basis, we are still good 😅!